config/routes.rb
Rails.application.routes.draw do
  devise_for :managers
  root 'dashboard#lorenzo'
  
  get 'dashboard/index'
  get 'dashboard/lorenzo'

  get '/bruno', to: 'dashboard#lorenzo'
  get '/financial/index', to: 'dashboard#index'
  get '/financial/entrada'
  get '/financial/saida'
  resources :dashboard, only: [:new, :create, :edit, :update, :destroy]
  resources :financial

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/employer.rb
class Employer < ApplicationRecord
end

app/models/financial.rb
class Financial < ApplicationRecord
end

app/models/manager.rb
class Manager < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :authenticate_manager!
    layout :set_layout
    
    def bruno
        return 'Brunooo'
    end

    def set_layout
        devise_controller? ? "manager_devise" : "manager"
    end
end

app/controllers/dashboard_controller.rb
class DashboardController < ApplicationController
  before_action :set_employer, only: [:edit,:update,:destroy]
  def index
    @financialIn = Financial.where(type_financial: 0)
    @financialOut = Financial.where(type_financial: 1)
  end
  
  def create
    usuario = Employer.new(set_params)
    usuario.save
    redirect_to "/dashboard/lorenzo"
  end

  def new
    @user = Employer.new()
  end
  
  def edit;end
  
  def update
    @user.update(set_params)
    redirect_to "/dashboard/lorenzo"
  end
  
  def destroy
    @user.destroy
    redirect_to "/dashboard/lorenzo"
  end

  def lorenzo
    @users = Employer.all.order("id ASC")
  end

  def set_employer
    @user = Employer.find(params[:id])
  end

  def set_params
    params.require(:employer).permit(:name,:age)
  end

end

app/controllers/financial_controller.rb
class FinancialController < ApplicationController
  before_action :set_financial, only: [:edit,:update]

  def entrada
    @financials = Financial.where(type_financial: 0)
  end

  def saida
    @financials = Financial.where(type_financial: 1)
  end

  def new
    @financial = Financial.new()
  end

  def create
    financeiro = Financial.new(set_params)
    financeiro.save
    redirect_to "/financial/entrada"
  end

  def edit; end

  def update
    @financial.update(set_params)
    redirect_to "/financial/entrada"
  end

  def set_financial
    @financial = Financial.find(params[:id])
  end

  def set_params
    params.require(:financial).permit(:type_financial,:name,:value)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/dashboard_helper.rb
module DashboardHelper

end

app/helpers/financial_helper.rb
module FinancialHelper

    def is_selected(type_financial, select_value)
        if type_financial == select_value
            return "selected"
        end
    end

end

app/views/dashboard/edit.html.erb
<h1>Dashboard#edit</h1>

<%= form_with(url: "/dashboard/#{@user.id}", method: :put, local: true, model: @financial) do |f| %>
    <label for="name">Name</label>
    <%= f.text_field :name, id: "name" %>
    <br>
    <label for="age">Age</label>
    <%= f.number_field :age, id: "age" %>

    <%= f.submit "Update" %>
<% end %>

app/views/dashboard/index.html.erb
<div class="row">
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-primary shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-primary text-uppercase mb-1">
                            Total de Entradas</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @financialIn.count %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-calendar fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-success shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-success text-uppercase mb-1">
                            Total de Saidas</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @financialOut.count %></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-dollar-sign fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Earnings (Monthly) Card Example -->
    <%# <div class="col-xl-3 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">Tasks
                        </div>
                        <div class="row no-gutters align-items-center">
                            <div class="col-auto">
                                <div class="h5 mb-0 mr-3 font-weight-bold text-gray-800">50%</div>
                            </div>
                            <div class="col">
                                <div class="progress progress-sm mr-2">
                                    <div class="progress-bar bg-info" role="progressbar"
                                        style="width: 50%" aria-valuenow="50" aria-valuemin="0"
                                        aria-valuemax="100"></div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-clipboard-list fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div> %>

    <div class="col-xl-2 col-md-6 mb-4">
        <div class="card border-left-info shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-info text-uppercase mb-1">
                            Valor Total Entrada</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @financialIn.sum(:value)%></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- Pending Requests Card Example -->
    <div class="col-xl-2 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Valor Total Saida</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @financialOut.sum(:value)%></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <div class="col-xl-2 col-md-6 mb-4">
        <div class="card border-left-warning shadow h-100 py-2">
            <div class="card-body">
                <div class="row no-gutters align-items-center">
                    <div class="col mr-2">
                        <div class="text-xs font-weight-bold text-warning text-uppercase mb-1">
                            Somatório Valor Total</div>
                        <div class="h5 mb-0 font-weight-bold text-gray-800"><%= @financialIn.sum(:value) + @financialOut.sum(:value)%></div>
                    </div>
                    <div class="col-auto">
                        <i class="fas fa-comments fa-2x text-gray-300"></i>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<% form_with(url: "/dashboard", method: :post, local: true) do |f| %>
    <label for="name">Name</label>
    <%= f.text_field :name, id: "name" %>
    <br>
    <label for="age">Age</label>
    <%= f.number_field :age, id: "age" %>

    <%= f.submit "Save" %>
<% end %>

app/views/dashboard/lorenzo.html.erb
<h1>Dashboard#lorenzo</h1>
<%= link_to "NEW", "/dashboard/new"%>
<br>
<br>
<% @users.each do |u| %>
<label>ID:</label>
<%= u.id %>
<br>
<%= u.name %>
<br>
<%= u.age %>
<br>
<%= link_to "SHOW", "/dashboard/#{u.id}/edit"%>
<%= link_to "DESTROY", "/dashboard/#{u.id}", :method => :delete, :data => { :confirm => "Are you sure?" }%>
<br>
<br>
<% end %>
<%= link_to "LOGOUT", destroy_manager_session_path %>
<%= current_manager.email%>

app/views/dashboard/new.html.erb
<h1>Dashboard#new</h1>
<%= form_with(url: "/dashboard", method: :post, local: true, model: @user) do |f| %>
    <label for="name">Name</label>
    <%= f.text_field :name, id: "name" %>
    <br>
    <label for="age">Age</label>
    <%= f.number_field :age, id: "age" %>

    <%= f.submit "Save" %>
<% end %>

app/views/financial/edit.html.erb
<h1>Financial#edit</h1>
<%= form_with(url: "/financial/#{@financial.id}", method: :put, model: @financial) do |f| %>
    <label for="type">Type</label>
    <select name="financial[type_financial]" id="type">
        <option value="0" <%= is_selected(@financial.type_financial, 0) %>>Entrada</option>
        <option value="1" <%= is_selected(@financial.type_financial, 1) %>>Saida</option>
    </select>
    <br>
    <label for="name">Name</label>
    <%= f.text_field :name, id: "name" %>
    <br>
    <label for="value">Value</label>
    <%= f.text_field :value, id: "value" %>
    <br>
    <%= f.submit "Salvar"%>
<% end %>

app/views/financial/entrada.html.erb
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Entrada</h6>
    </div>
        <div class="card-body">
            <%= link_to "+", new_financial_path, class: "btn btn-primary mb-2 float-right" %>
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Value</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Value</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                    <% @financials.each do |f|%>
                        <tr>
                            <td><%= f.id %></td>
                            <td><%= f.name %></td>
                            <td><%= f.value %></td>
                            <td><%= link_to "Editar", edit_financial_path(f.id) %></td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

app/views/financial/new.html.erb
<h1>Financial#new</h1>
<%= form_with(url: "/financial", method: :post, model: @financial) do |f| %>
    <label for="type">Type</label>
    <select name="financial[type_financial]" id="type">
        <option value="0">Entrada</option>
        <option value="1">Saida</option>
    </select>
    <br>
    <label for="name">Name</label>
    <%= f.text_field :name, id: "name" %>
    <br>
    <label for="value">Value</label>
    <%= f.text_field :value, id: "value" %>
    <br>
    <%= f.submit "Criar"%>
<% end %>

app/views/financial/saida.html.erb
<div class="card shadow mb-4">
    <div class="card-header py-3">
        <h6 class="m-0 font-weight-bold text-primary">DataTables Saida</h6>
    </div>
        <div class="card-body">
            <%= link_to "+", new_financial_path, class: "btn btn-primary mb-2 float-right" %>
            <div class="table-responsive">
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Value</th>
                            <th>Actions</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>ID</th>
                            <th>Name</th>
                            <th>Value</th>
                            <th>Actions</th>
                        </tr>
                    </tfoot>
                    <tbody>
                        <% @financials.each do |f|%>
                        <tr>
                            <td><%= f.id %></td>
                            <td><%= f.name %></td>
                            <td><%= f.value %></td>
                            <td><%= link_to "Editar", edit_financial_path(f.id) %></td>
                        </tr>
                    <% end %>
                    </tbody>
                </table>
            </div>
        </div>
    </div>

app/views/layouts/manager.html.erb
<%# <%= yield %>
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Dashboard</title>

    <!-- Custom fonts for this template-->
    <link href="/template/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/template/css/sb-admin-2.min.css" rel="stylesheet">

</head>

<body id="page-top">

    <!-- Page Wrapper -->
    <div id="wrapper">

        <!-- Sidebar -->
        <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">

            <!-- Sidebar - Brand -->
            <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
                <div class="sidebar-brand-icon rotate-n-15">
                    <i class="fas fa-laugh-wink"></i>
                </div>
                <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
            </a>

            <!-- Divider -->
            <hr class="sidebar-divider my-0">

            <!-- Nav Item - Dashboard -->
            <li class="nav-item active">
                <a class="nav-link" href="index.html">
                    <i class="fas fa-fw fa-tachometer-alt"></i>
                    <span>Dashboard</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Cadastro
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <!-- Nav Item - Tables -->
            <li class="nav-item">
                <a class="nav-link" href="tables.html">
                    <i class="fas fa-fw fa-user"></i>
                    <span>Usuários</span></a>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider">

            <!-- Heading -->
            <div class="sidebar-heading">
                Financeiro
            </div>

            <!-- Nav Item - Pages Collapse Menu -->
            <li class="nav-item">
                <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages"
                    aria-expanded="true" aria-controls="collapsePages">
                    <i class="fas fa-fw fa-dollar-sign"></i>
                    <span>Financeiro</span>
                </a>
                <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
                    <div class="bg-white py-2 collapse-inner rounded">
                        <%# <h6 class="collapse-header">Login Screens:</h6> %>
                        <%= link_to "Entrada", financial_entrada_path, class: "collapse-item" %>
                        <%= link_to "Saida", financial_saida_path, class: "collapse-item"%>
                    </div>
                </div>
            </li>

            <!-- Divider -->
            <hr class="sidebar-divider d-none d-md-block">

            <!-- Sidebar Toggler (Sidebar) -->
            <div class="text-center d-none d-md-inline">
                <button class="rounded-circle border-0" id="sidebarToggle"></button>
            </div>

        </ul>
        <!-- End of Sidebar -->

        <!-- Content Wrapper -->
        <div id="content-wrapper" class="d-flex flex-column">

            <!-- Main Content -->
            <div id="content">

                <!-- Topbar -->
                <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

                    <!-- Sidebar Toggle (Topbar) -->
                    <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
                        <i class="fa fa-bars"></i>
                    </button>

                    <!-- Topbar Navbar -->
                    <ul class="navbar-nav ml-auto">

                        <!-- Nav Item - Search Dropdown (Visible Only XS) -->
                        <li class="nav-item dropdown no-arrow d-sm-none">
                            <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <i class="fas fa-search fa-fw"></i>
                            </a>
                            <!-- Dropdown - Messages -->
                            <div class="dropdown-menu dropdown-menu-right p-3 shadow animated--grow-in"
                                aria-labelledby="searchDropdown">
                                <form class="form-inline mr-auto w-100 navbar-search">
                                    <div class="input-group">
                                        <input type="text" class="form-control bg-light border-0 small"
                                            placeholder="Search for..." aria-label="Search"
                                            aria-describedby="basic-addon2">
                                        <div class="input-group-append">
                                            <button class="btn btn-primary" type="button">
                                                <i class="fas fa-search fa-sm"></i>
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </li>

                        <div class="topbar-divider d-none d-sm-block"></div>

                        <!-- Nav Item - User Information -->
                        <li class="nav-item dropdown no-arrow">
                            <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button"
                                data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_manager.email %></span>
                            </a>
                            <%# <!-- Dropdown - User Information -->
                            <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in"
                                aria-labelledby="userDropdown">
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Profile
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Settings
                                </a>
                                <a class="dropdown-item" href="#">
                                    <i class="fas fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Activity Log
                                </a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                                    <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                                    Logout
                                </a>
                            </div> %>
                        </li>

                    </ul>

                </nav>
                <!-- End of Topbar -->

                <!-- Begin Page Content -->
                <div class="container-fluid">
                    <%= yield %>
                </div>
                <!-- /.container-fluid -->

            </div>
            <!-- End of Main Content -->

            <!-- Footer -->
            <footer class="sticky-footer bg-white">
                <div class="container my-auto">
                    <div class="copyright text-center my-auto">
                        <span>Copyright &copy; Your Website 2021</span>
                    </div>
                </div>
            </footer>
            <!-- End of Footer -->

        </div>
        <!-- End of Content Wrapper -->

    </div>
    <!-- End of Page Wrapper -->

    <!-- Scroll to Top Button-->
    <a class="scroll-to-top rounded" href="#page-top">
        <i class="fas fa-angle-up"></i>
    </a>

    <%# <!-- Logout Modal-->
    <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
        aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">×</span>
                    </button>
                </div>
                <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
                    <a class="btn btn-primary" href="login.html">Logout</a>
                </div>
            </div>
        </div>
    </div> %>

    <!-- Bootstrap core JavaScript-->
    <script src="/template/vendor/jquery/jquery.min.js"></script>
    <script src="/template/vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="/template/vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="/template/js/sb-admin-2.min.js"></script>

    <!-- Page level plugins -->
    <script src="/template/vendor/chart.js/Chart.min.js"></script>

    <!-- Page level custom scripts -->
    <script src="/template/js/demo/chart-area-demo.js"></script>
    <script src="/template/js/demo/chart-pie-demo.js"></script>

</body>

</html>

app/views/layouts/manager_devise.html.erb
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>SB Admin 2 - Login</title>

    <!-- Custom fonts for this template-->
    <link href="/template/vendor/fontawesome-free/css/all.min.css" rel="stylesheet" type="text/css">
    <link
        href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i"
        rel="stylesheet">

    <!-- Custom styles for this template-->
    <link href="/template/css/sb-admin-2.min.css" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body class="bg-gradient-primary">

    <div class="container">

        <!-- Outer Row -->
        <div class="row justify-content-center">

            <div class="col-xl-10 col-lg-12 col-md-9">

                <div class="card o-hidden border-0 shadow-lg my-5">
                    <div class="card-body p-0">
                        <!-- Nested Row within Card Body -->
                        <div class="row">
                            <div class="col-lg-6 d-none d-lg-block bg-login-image"></div>
                            <div class="col-lg-6">
                                <div class="p-5">
                                    <div class="text-center">
                                        <h1 class="h4 text-gray-900 mb-4">Bem vindo ao sistema financeiro!</h1>
                                    </div>
                                    <%= yield %>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>

        </div>

    </div>

    <!-- Bootstrap core JavaScript-->
    <script src="vendor/jquery/jquery.min.js"></script>
    <script src="vendor/bootstrap/js/bootstrap.bundle.min.js"></script>

    <!-- Core plugin JavaScript-->
    <script src="vendor/jquery-easing/jquery.easing.min.js"></script>

    <!-- Custom scripts for all pages-->
    <script src="js/sb-admin-2.min.js"></script>

</body>

</html>

app/views/managers/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/managers/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>